### ISSUE TITLE
issue ingestr installation_ undefined exports: plot_fapar_ingestr

### ISSUE THREAD

**Issue by mpeaucelle** [stineb/ingestr#1]
Beni, 
There is a small bug during the installation of your ingestr package. 

if(!require(devtools)){install.packages(devtools)}
Le chargement a nécessité le package : devtools
Le chargement a nécessité le package : usethis
> devtools::install_github( "stineb/ingestr" )
Downloading GitHub repo stineb/ingestr@master
✓  checking for file ‘/tmp/RtmpMNMMLF/remotes22cae7146e8/stineb-ingestr-da714a0/DESCRIPTION’ ...
─  preparing ‘ingestr’:
✓  checking DESCRIPTION meta-information ...
─  checking for LF line-endings in source and make files and shell scripts
─  checking for empty or unneeded directories
─  building ‘ingestr_0.1.0.tar.gz’
   
Installing package into ‘/home/marc/R/x86_64-pc-linux-gnu-library/3.5’
(as ‘lib’ is unspecified)
* installing *source* package ‘ingestr’ ...
** R
** byte-compile and prepare package for lazy loading
Note: ... may be used in an incorrect context 
** help
*** installing help indices
** building package indices
** installing vignettes
** testing if installed package can be loaded
Error: package or namespace load failed for ‘ingestr’ in namespaceExport(ns, exports):
 undefined exports: plot_fapar_ingestr, plot_fapar_ingestr_bysite
Erreur : le chargement a échoué
Exécution arrêtée
ERROR: loading failed
* removing ‘/home/marc/R/x86_64-pc-linux-gnu-library/3.5/ingestr’
Erreur : Failed to install 'ingestr' from GitHub:
  (converti depuis l'avis) installation of package ‘/tmp/RtmpMNMMLF/file22ca2e6a5407/ingestr_0.1.0.tar.gz’ had non-zero exit status

**Comment by stineb** [comment]
Thanks, Marc. The source file `plot_fapar_ingestr.R` was missing in the repo. Resolved now.
