### ISSUE TITLE
MODISTools download issue

### ISSUE THREAD

**Issue by khufkens** [stineb/ingestr#2]
Can't seem to reproduce the error which reads

```
Error in (function (..., row.names = NULL, check.rows = FALSE, check.names = TRUE,  :
```

Worked example below functions.

```
library(tidyverse)
library(ingestr)

# load in meta-data fluxnet2015
# from ingestr package
load("data/siteinfo_fluxnet2015.RData")

# only select first few sites
df <- siteinfo_fluxnet2015
df <- df[1:20,]

# set settings for data download
settings_modis <- get_settings_modis(
  bundle            = "modis_fpar",
  data_path         = "~/data/modis_subsets/",
  method_interpol   = "loess",
  keep              = TRUE,
  overwrite_raw     = FALSE,
  overwrite_interpol= TRUE,
  n_focal           = 0
)

# add required start and end dates
df <- df %>% 
  mutate(date_start = "2010-01-01",
         date_end = "2010-12-31")

# execute the ingest
df_modis_fpar <- ingest(
  siteinfo = df,
  source = "modis",
  settings = settings_modis, 
  parallel = FALSE,
  #ncores = 2
)
```

**Comment by khufkens** [comment]
@stineb @lauramarques could you provide reprex example with driver data to support debugging. Just an error statement is rather useless.

**Comment by lauramarques** [comment]
I got that error yesterday when using the mt_subset fc for several sites in a loop and for several bands. It works for me now.

`pheno_all <- data.frame() 

for(i in 1:25) {
  
pheno_sub <- mt_subset(
  product = "MCD12Q2",
  lat = sampled_pixels$lat[i],
  lon = sampled_pixels$lon[i],
  band = c("Greenup.Num_Modes_01",
           "Greenup.Num_Modes_02",
           "MidGreendown.Num_Modes_02"),
  start = "2001-01-01",
  end = "2018-01-01",
  km_lr = 0,
  km_ab = 0,
  site_name = "testsite",
  internal = TRUE,
  progress = FALSE)

pheno_all <- rbind(pheno_all, pheno_sub)

}`

However, when using the mt_batch_subset fc again for several sites and bands, I still got this other error:

`Error in `$<-.data.frame`(`*tmp*`, "band", value = c("Greenup.Num_Modes_01",  : 
  replacement has 2 rows, data has 25`

`pheno_SOS <- mt_batch_subset(df = sampled_pixels[1:25,],
                             product = "MCD12Q2",
                             band = c("Greenup.Num_Modes_01",
                                      "Greenup.Num_Modes_02"),
                             km_lr = 0,
                             km_ab = 0,
                             start = "2001-01-01",
                             end = "2018-01-01",
                             internal = TRUE)`

**Comment by khufkens** [comment]
Input is a data frame (not a tibble as this can hold additional nested data as a list) with columns [site_name, lon, lat] - check this formatting!

```
sampled_pixels <- sampled_pixels %>% 
  rename(
    "site_name" = "sitename") %>%
  data.frame()
```

Best to limit the number of cores to 2, maybe 4. ORNL has been enforcing rate limiting (multiple connections, but there is no formal "number" for it.

```
library(tidyverse)
library(ingestr)
library(MODISTools)

# load in meta-data fluxnet2015
# from ingestr package
df <- ingestr::siteinfo_fluxnet2015

# only select first two sites
df <- siteinfo_fluxnet2015
df <- df %>% 
  rename(
    "site_name" = "sitename") %>%
  data.frame()

pheno_SOS <- mt_batch_subset(
  df = df[1:20,],
  product = "MCD12Q2",
  band = c("Greenup.Num_Modes_01"),
  km_lr = 0,
  km_ab = 0,
  start = "2001-01-01",
  end = "2018-01-01",
  internal = TRUE,
  ncores = 2)
```

**Comment by stineb** [comment]
I have a hard time creating a reproducible example. I suspect errors happen when something goes wrong with the download. Could such crashes be caught inside `mt_subset` somehow and the code would automatically re-try downloading without crashing?

I tried the following for reproducing problems. I guess this is mainly arising when getting a lot of data at once (multiple bands, multiple pixels).

```
library(tidyverse)
library(ingestr)
library(MODISTools)

# load in meta-data fluxnet2015
# from ingestr package
df <- ingestr::siteinfo_fluxnet2015

## this works: single pixel, multiple bands
rm("df_modis_0p_1b")
df_modis_0p_1b <- mt_subset(
  lat       = df$lat[1],                        # latitude
  lon       = df$lon[1],                        # longitude
  product = "MOD09A1",
  band = c("sur_refl_b01", "sur_refl_b02"),
  km_lr = 0,
  km_ab = 0,
  start = "2001-01-01",
  end = "2002-01-01",
  site_name = df$sitename[1],
  internal = TRUE,
  progress = TRUE
  )
head(df_modis_0p_1b)

## this works: multiple pixels, single band
rm("df_modis_1p_0b")
df_modis_1p_0b <- mt_subset(
  lat       = df$lat[1],                        # latitude
  lon       = df$lon[1],                        # longitude
  product = "MOD09A1",
  band = "sur_refl_b01",
  km_lr = 1.0,
  km_ab = 1.0,
  start = "2001-01-01",
  end = "2002-01-01",
  site_name = df$sitename[1],
  internal = TRUE,
  progress = TRUE
  )
head(df_modis_1p_0b)

## this DOES NOT ALWAYS work: multiple pixels, multiple bands
rm("df_modis_1p_1b")
df_modis_1p_1b <- mt_subset(
  lat       = df$lat[1],                        # latitude
  lon       = df$lon[1],                        # longitude
  product = "MOD09A1",
  band = c("sur_refl_b01", "sur_refl_b02"),
  km_lr = 1.0,
  km_ab = 1.0,
  start = "2001-01-01",
  end = "2002-01-01",
  site_name = df$sitename[1],
  internal = TRUE,
  progress = TRUE
)
head(df_modis_1p_1b)

# Error message when it crashes:
# Error in do.call("rbind", subset_data$data) : 
#   second argument must be a list

## this works sometimes : multiple pixels, many bands
rm("df_modis_1p_xb")
df_modis_1p_xb <- mt_subset(
  lat       = df$lat[1],                        # latitude
  lon       = df$lon[1],                        # longitude
  product = "MOD09A1",
  band = c("sur_refl_b01", "sur_refl_b02", "sur_refl_qc_500m", "sur_refl_state_500m", "sur_refl_raz", "sur_refl_szen", "sur_refl_vzen"),
  km_lr = 0.0,
  km_ab = 0.0,
  start = "2001-01-01",
  end = "2002-01-01",
  site_name = df$sitename[1],
  internal = TRUE,
  progress = TRUE
)
head(df_modis_1p_xb)

## ... and sometimes not:
# Error in do.call("rbind", subset_data$data) : 
#   second argument must be a list

## and another time I get this:
# Error in (function (..., row.names = NULL, check.rows = FALSE, check.names = TRUE,  : 
#                       arguments imply differing number of rows: 1, 0

```

**Comment by khufkens** [comment]
Yes, to some extend this can be done but most of the time it won't resolve the issue. When crashes happen the service is generally slow or throttled. 

Restarting a run will in some ways only make it worse. I should check the code, but technically the API only provides chunks of 10 temporal returns at a time (I should check if this still is in place!). Requesting lots of temporal data in short succession might get you throttled down, giving rise to these errors (or breaking previous progress). Having people work on the same domain (university campus etc), will potentially inflate the issue (and might also be the reason why I rarely see these issues from home - Wednesday is server maintenance day - generally slower).

They certainly cut back on parallel issues. You can query more data for fixed sites (including most fluxnet locations). These datasets are buffered and are quicker.

```
# list all sites
mt_sites()
```

The call below runs in less than 30s.

```
# random OZFLUX site
df_modis_1p_xb <- mt_subset(
  site_id = "au_tasmania_warra",
  product = "MOD09A1",
  band = c("sur_refl_b01",
           "sur_refl_b02",
           "sur_refl_qc_500m",
           "sur_refl_state_500m",
           "sur_refl_raz",
           "sur_refl_szen",
           "sur_refl_vzen"),
  km_lr = 0.0,
  km_ab = 0.0,
  start = "2001-01-01",
  end = "2002-01-01",
  internal = TRUE,
  progress = TRUE
)
```

**Comment by stineb** [comment]
How would I use the argument `site_id` and `network` if I wanted to download subsets for FLUXNET site "CH-Lae" (or any other site for that matter, using FLUXNET standard site names)?

I can find [this](https://modis.ornl.gov/sites/?id=ch_aargau_laegern). But apparently, the relevant site ID is `ch_aargau_laegern` and not `CH-Lae` as in FLUXNET. Is there a table for associating these site IDs with FLUXNET standard names?

**Comment by khufkens** [comment]
Not that I know of. It can be made, but needs to be validated.

**Comment by stineb** [comment]
Oh, wow. This actually works like a charm, using `CH-Lae` and `FLUXNET`:

```
df_modis_1p_xb_id <- mt_subset(
  product = "MOD09A1",
  band = c("sur_refl_b01", "sur_refl_b02", "sur_refl_qc_500m", "sur_refl_state_500m", "sur_refl_raz", "sur_refl_szen", "sur_refl_vzen"),
  km_lr = 1.0,
  km_ab = 1.0,
  start = "2001-01-01",
  end = "2002-01-01",
  site_id = "CH-Lae",
  network = "FLUXNET",
  internal = TRUE,
  progress = TRUE
)
```

**Comment by khufkens** [comment]
Ok, implemented the API completely it seems. I forget these things.

**Comment by khufkens** [comment]
Better, I should write more manuals

**Comment by stineb** [comment]
The problem was apparently on the ORNL DAAC side. When the download crashes, the entire function  `MODISTools::mt_subset()`  crashes. This chance that this happens increases further when downloading multiple bands at once. This is now solved by using `try()` and re-trying when failed after a 3 seconds "sleep", and downloading data for each band with a separate call to  `MODISTools::mt_subset()`. See [here](https://github.com/stineb/ingestr/blob/830907e6ef9b2d5220f0444a734ec3042f5ad9ed/R/ingest_modis_bysite.R#L61).
