### ISSUE TITLE
etopo for extracting elevation - not so stable

### ISSUE THREAD

**Issue by yunkepeng** [stineb/ingestr#7]
By using `ingest` to get elevation, basing on lon, lat and site-name. The output elevation is not so 'stable'. See below example:

![image](https://user-images.githubusercontent.com/62582250/132504397-5f9b044c-3fb1-4265-9f09-ea3987ccf55e.png)

In nearly the same coordinates, one output of elevation is negative. Not sure how to best address this...

**Comment by khufkens** [comment]
Hi @yunkepeng could you include demo code this would make it easier to debug.

**Comment by yunkepeng** [comment]
Thank you Koen and I think I have now found the solution. Lon and lat should not be replicated. Taking an example below, example 1 should be changed to example 2 (to remove the replicates), and after this, the issue was solved (though I am not sure why..)

**Example 1:**
  lon           lat          sitename
147.2700 -42.7000       c1
175.2700 -40.2300       c2
175.2700 -40.2300       c2

**Example 2:**
  lon           lat          sitename
147.2700 -42.7000       c1
175.2700 -40.2300       c2

**Comment by khufkens** [comment]
Most likely ingestr only processes unique sites, if you provide multiple sites with the same name and coordinates the returned list will be shorter than the one provided. Appending the one to the other shifts the whole lot by how many cases you have like this.
